### ISSUE TITLE
Is this tool compatible to only import the inherited process..?? then can i modify the changes to exported json file and import the same on to another account?

### ISSUE THREAD

**Issue by rakeshkasoju** [Microsoft/process-migrator#10]

**Comment by liang2zhu1** [comment]
Only inherited process is supported - if you are on XML customization you can import/export zip today. 
You should avoid modifying the content in general - as it's not guaranteed to work.

**Comment by rakeshkasoju** [comment]
'Hi Liang,

Thanks for the information

Yes, tool is compatible with inherited process model.
I have few questions

  1.  I just want to only export the inherited process from one instance to my local machine and do some changes to the .JSON file and I want to import onto  another instance. Is it possible???
  2.  When we only export the inherited process, Is it mandatory to enter the "targetAccountUrl" and "targetAccountToken" in the configuration.json file

Command used to export the process Process-Migrator  --mode:Export --config="Path\configuration.json"
Let me know if you need any other information

Regards,
Rakesh
________________________________

**Comment by liang2zhu1** [comment]
I would probably say nothing stop you from doing #1 on technology side :) , it would technically work but you can easily break things since the possible combination is more than what VSTS web UI provides. 
#2 I got similar feedback so I'll update document, you don't have to put that.
