### ISSUE TITLE
[DEP0049] DeprecationWarning: The `util.isFunction` API is deprecated.  Please use `typeof arg === "function"` instead.

### ISSUE THREAD

**Issue by MicE44** [microsoft/process-migrator#103]
Hi Devs,
I use version 10.8.1 and I got these Warning.

`[DEP0049] DeprecationWarning: The `util.isFunction` API is deprecated.  Please use `typeof arg === "function"` instead.`

fyi for the next versions ;-)

cya

**Comment by AminTi** [comment]
Hi, Could you please clarify what version 10.8.1 refers to?

**Comment by AminTi** [comment]
If you're still experiencing the same issue, please open a new issue so we can address it accordingly.
