### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by gcmbmealey** [microsoft/process-migrator#105]
I'm getting this error still (similar thread closed with no resolution).  I've tried with a PAT that has full access to all orgs and one with full access to the source org.

Failed to connect to account 'https://dev.azure.com/<ourorg>' using personal access token '<omitted>' provided, check url and token.

**Comment by AminTi** [comment]
Hi, I just tested it and it works as expected. Can you describe your environment? Also, can you check if you get any errors in the browser console or network log

**Comment by gcmbmealey** [comment]
I just tried again and it is working - not sure what happened before. Thanks
