### ISSUE TITLE
What to do with the number of picklists in the collection has reached the limit of 512

### ISSUE THREAD

**Issue by rakeshkasoju** [microsoft/process-migrator#13]
We are getting the below issue when we fix the issue and re run the process-migrator to a vanilla instance

Exception message:VS402846: The number of picklists in the collection has reached the limit of 512.
Call stack:Error: VS402846: The number of picklists in the collection has reached the limit of 512.
    at RestClient.<anonymous> (C:\Users\v-karake\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:173:28)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\v-karake\AppData\Roaming\npm\node_modules\process-migrator\node_modules\vso-node-api\node_modules\typed-rest-client\RestClient.js:6:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[ERROR] [2018-06-27T11:39:44.095Z] Import failed, see log file for details. Failed to create picklist for field SCM_Dynamics_SSE_D365.365TargetCodeDrop, see logs for details.

Please suggest

**Comment by rakeshkasoju** [comment]
Please suggest for the work around for this

**Comment by liang2zhu1** [comment]
Can you provide your VSTS account name? I'll update you shortly - I'm discussing with the owning team on the guidance here.

**Comment by rakeshkasoju** [comment]
Hi Liang,

Sorry for the delay in response

Please find the VSTS Account : https://inherited.visualstudio.com/

Please check and let us know for the workaround

**Comment by liang2zhu1** [comment]
You may remove unused picklist by [getting all picklists](https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/lists/get?view=azure-devops-rest-5.0) and [all fields](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/fields/list?view=azure-devops-rest-5.0) and remove the picklist that is not referenced by field - which means no field has a 'picklistId' property matching the picklist id.
