### ISSUE TITLE
Inherited Process Template named SCRUMUA didn't get exported to my other VSTS Account. Can you please do let me know what am i doing wrong.

### ISSUE THREAD

**Issue by mumairabbasi** [microsoft/process-migrator#18]
Hi ,

1.	I installed the NPM through the “node-v8.11.3-x64”  from your link and it installed successfully.
2.	Then I create the PAT from both the Source VSTS account and from the Target VSTS account.
3.	Then I manually created the Configuration.json file.
4.	The Configuration.json file is in the attachments for your review, I changed the PATs from it for 
         security reason.
5.	Then I ran the Node.Exe file.
6.	Command Prompt open and there I ran the command  
        process-migrator [--mode=<migrate(default)/import/export> [--config=<your-configuration-file- 
         path>]

Which I ran on my machine like this:-

process [export [--config=C:\Users\uabbasi\Documents\configuration.json]

But the TFS Process Template named SCRUMUA didn’t get exported to Target VSTS account.

I think the command i am running is incorrect so can you please let me know how to correct this command And if something else is missing or incorrect then can you please do let me know that.

If possible can you please share any video or stepbystep guide regarding how to use this process migrator which shall by very helpful for us.

I have attached the node.exe command prompt image and also the configuration.json file in this ticket.

![process-migrator_command_running_through_node exe_on_comand_prompt](https://user-images.githubusercontent.com/41396331/42909789-48a8e9fc-8ab3-11e8-8b1e-4b0274e11fd0.png)

[configuration.zip](https://github.com/Microsoft/process-migrator/files/2207477/configuration.zip)

**Comment by mumairabbasi** [comment]
Hi ,

Can you please help me, as no reply has been received yet on my issue posted on 18th July.

Thanks,
Umair Abbasi.

**Comment by nschonni** [comment]
Don't run `node.exe` first. When you install packages through NPM it adds executable commandline files in your path. Just open a regular command prompt and run the command

**Comment by mumairabbasi** [comment]
Hi ,

Thanks for your reply.  Can you please check my Configuration.json File that is present in the attachments above and please can you do let me know that exact command that i shall run, the command which i ran above in the image is it correct ? please reply.

Thanks,
Umair Abbasi.

**Comment by nschonni** [comment]
Sorry, I haven't actually used this tool, my comment was just based on general Node/NPM conventions and seeing your screenshot.
PS: Email attachments don't work for GitHub issues, you can only add files on the web.

**Comment by nschonni** [comment]
I'm not a Microsoft employee, I'm just giving you some general advice based on reading your issue
PS: You've posted you token that you might want to revoke now https://github.com/Microsoft/process-migrator#-configuration-file-has-pat-right-protect-it-

**Comment by mumairabbasi** [comment]
Hi ,

So can you please guide me to whom shall i contact in this regard. 
And this token is incorrect and incomplete purposely and i shall also delete it from my vsts account too.

Thanks,
Umair Abbasi.
