### ISSUE TITLE
GUIDs and name strings in process.json

### ISSUE THREAD

**Issue by tobiasschmailzl** [Microsoft/process-migrator#20]
After exporting and looking at the process.json, there seems to be namings and guids that won't be replaced on import. does this make trouble in future?

**Comment by liang2zhu1** [comment]
These are for informational purpose (for export) and also used as the identifier for some of the import by the tool itself (like picklist) but not consumed by target Azure DevOps organization.
Basically the tool calls all public/documented REST API on Azure DevOps when creating each artifact (Work Item Type, Field, Rule, State, Behavior, Form field/group/page, etc) and a new Guid is specified on server side and
