### ISSUE TITLE
Documentation incorrect for LogLevel.

### ISSUE THREAD

**Issue by MrHinsh** [Microsoft/process-migrator#21]
Documentation states:

`"logLevel":"Optional, log level for console. Possibe values are 'Verbose'/'Information'/'Warning'/'Error'.",`

When it should be:

`"logLevel":"Optional, log level for console. Possibe values are 'verbose'/'information'/'warning'/'error'.",`

Setting logLevel to "Verbose" results in error

+ Also note spelling error in docs "Possibe" should be "Possible"

**Comment by liang2zhu1** [comment]
Thanks fix this hence closing this
