### ISSUE TITLE
Overwriting existing fields

### ISSUE THREAD

**Issue by rfennell** [Microsoft/process-migrator#29]
I want to just ask a question about usage before I try something. Just in case there is a better way, or I have  blocked myself and am wasting my time.

## Background
I have two Azure DevOps instances, both with, in theory, the same inherited template. This has up to now been kept in sync manually; hence the 'in theory' 

I have some custom fields in these templates. 

## Problem 
If I try to do a migrate from one instance to another I get the error

`Import failed, see log file for details. Create field 'Location' failed, see log for details.`

On looking at the code I can't see any flag or handing for overwriting an existing field. But after a bit more thought I realised that this might not be straight forward. An overwrite would only work if the only reference to the field was by name (no GUID used or the like)

## Options
The options I see are

- Delete the field definition on the target instance, but this will result in data loss (I think)
- Write some re-mapper - something I would like to avoid

Any comments or have I missed something obvious?

**Comment by rfennell** [comment]
Thanks to @MrHinsh I got the answer

You will need to:

1. Add a new field to store the data.
1. Use the Migration Tools to move the data from the original to this new field
3. Delete that field
4. Migrate the process

**Comment by jessehouwing** [comment]
That's a nice workaround, but it doesn't make it efficient to quickly replicate multiple process templates that share fields from one account to another.

Instead, it should do a compatibility check and then just *use the existing field*.
