### ISSUE TITLE
PAT Permissions

### ISSUE THREAD

**Issue by Gizmo0815** [microsoft/process-migrator#32]
Thanks for this great tool! During migration I run into an "Error getting process on source account" and I'm asked to check the token permissions. Could you please advise which scopes are required to read/write a process? I don't want to give full access if not absolutely necessary.

**Comment by liang2zhu1** [comment]
@Gizmo0815 It's expected to need `WorkItem Read, Write & Manage` permission. Feel free to reopen the issue if it's not the case and attach log.
