### ISSUE TITLE
connect ETIMEDOUT 13.107.6.183:443

### ISSUE THREAD

**Issue by jayashreeckonganda** [microsoft/process-migrator#33]
Hi ,

Getting below error when trying to migrate the process template.

connect ETIMEDOUT 13.107.6.183:443
Exception message:connect ETIMEDOUT 13.107.6.183:443
Call stack:Error: connect ETIMEDOUT 13.107.6.183:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
[ERROR] [2019-06-20T07:34:01.009Z] Import failed, see log file for details. Failed to add field 'Custom.ScrumMaster' to work item type 'PhilipsAgileProcess.IterationReport', see logs for details.

Please help

**Comment by Chintunie** [comment]
I am seeing the same error

**Comment by liang2zhu1** [comment]
@jayashreeckonganda  @Chintunie  I'm having difficulty to reproduce the issue, by error message that sounds like a network related issue, probably is related to specific Azure DevOps organization - could you please attach the full log, preferably also the exported xml as well, or send it to me (liangzhu at microsoft dot com)?  AB#1561992

**Comment by liang2zhu1** [comment]
I'm closing this for now - if this continues to happen please reactivate

**Comment by richa89s** [comment]
Hi, I have been trying an import on different Org's. Even tried with the same org as source and target. Getting the same error.

VERBOSE] [2022-07-08T06:06:25.437Z] Exception message:connect ETIMEDOUT 13.107.42.20:443
Call stack:Error: connect ETIMEDOUT 13.107.42.20:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)
[ERROR] [2022-07-08T06:06:25.441Z] Import failed, see log file for details. Unable to add 'Custom.Completed3' control to group 'Agile.User Story.User Story.Classification' in page 'Agile.User Story.User Story' in 'SITA-SAB-Borders.UserStory'. Error: connect ETIMEDOUT 13.107.42.20:443

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you.
