### ISSUE TITLE
Import fails with timeout error

### ISSUE THREAD

**Issue by Chintunie** [microsoft/process-migrator#35]
Hi,

I am trying to import a process from one organisation to another. The export works fine, however the import fails with the below error message.

`Exception message:connect ETIMEDOUT 13.107.42.20:443
Call stack:Error: connect ETIMEDOUT 13.107.42.20:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)`

The failure happens during the middle of the import process. Therefore, the process gets created in the target org but not 100% complete since the import got timed out.

If i delete the process in the target org and do a re-import, it again fails during the middle of the import process due to the timeout error. There is no specific pattern to determine when it times out. Sometimes it imports approx 80% of the process, sometimes 60% and sometimes 50% and times out.

**Comment by Chintunie** [comment]
Just checking if anyone got a chance to review this issue. Let me know if any log files are required.

**Comment by sonalijagtap** [comment]
Is this error resolved? i am getting the same issue. following is the error message 
Exception message:connect ETIMEDOUT 13.107.42.20:443
Call stack:Error: connect ETIMEDOUT 13.107.42.20:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[ERROR] [2020-11-20T13:13:55.138Z] Import failed, see log file for details. Create field 'XXXXX' failed, see log for details.

**Comment by The-Judge** [comment]
I have a similar error but with slightly different error. Also, export works fine, but during import, I receive the following message always, no matter how often I try:

```
[VERBOSE] [2021-02-01T13:03:46.865Z] Begin step 'Import work item types on target process'.
[VERBOSE] [2021-02-01T13:04:25.867Z] Exception message:read ETIMEDOUT
Call stack:Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
[ERROR] [2021-02-01T13:04:25.867Z] Import failed, see log file for details. Failed to create work item type 'MoE.Epic, see logs for details.
```

**Comment by WillShi-cn** [comment]
It seems I have same issue here.

[VERBOSE] [2022-07-04T05:41:20.108Z] Exception message:connect ETIMEDOUT 13.107.42.20:443
Call stack:Error: connect ETIMEDOUT 13.107.42.20:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ERROR] [2022-07-04T05:41:20.109Z] Import failed, see log file for details. Failed to edit HTML control 'System.Description in group'Agile.Issue.Issue.Description.WideGroup' in page 'Agile.Issue.Issue', see logs for details.

**Comment by richa89s** [comment]
same issue,can someone please help on this?

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.

**Comment by The-Judge** [comment]
That ruins the 4-year-anniversary 😅
