### ISSUE TITLE
Exported process typeId isn't being used when creating new Process on import.

### ISSUE THREAD

**Issue by kkrickster** [microsoft/process-migrator#36]
I'm using another tool to copy projects over to my new Organization. So the Process Template must have the same typeId as the original source

However, the typeId for the process isn't being used in the import process when creating the Process Template. It's creating a new one on import.

**Comment by liang2zhu1** [comment]
Fair - I'm going to raise a PR on this shortly

**Comment by liang2zhu1** [comment]
Actually - this needs some change on [Process Create API](https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/processes/create?view=azure-devops-rest-5.1) to support specify a GUID, I'll talk to the team owning this

**Comment by liang2zhu1** [comment]
@kkrickster can you use the reference name? I can make a change to keep reference name and that won't require a change from Azure DevOps service

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
