### ISSUE TITLE
Support field (control) and group order

### ISSUE THREAD

**Issue by sawpresto** [microsoft/process-migrator#38]
When migrating custom and inherited fields and groups, the custom controls/groups are moved to the last placement in the UI (not retaining order). I've opened a PR for this that should retain ordering. [url](https://github.com/microsoft/process-migrator/pull/37)

**Comment by liang2zhu1** [comment]
Thanks raising this PR - I approved with a tiny suggestion

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
