### ISSUE TITLE
Process Migrator Import works in one target site but fails with different errors in another target organization

### ISSUE THREAD

**Issue by sivasakthimurugesan** [microsoft/process-migrator#39]
hi Team,

I am using Process Migrator to migrate my inherited process from one organization to another in Azure Devops. I did not face any issue while migating to my personal organization. I tries changing the target account and retriggered migration to a different sit. however the same process was failing while import into the second target Organization, whereas it was working fine for the first target organization without any errors. Requesting your help asap.
Errors i got:
1.First time I got the below error:
Import failed, see log file for details. Unable to add 'Microsoft.VSTS.CMMI.Committed' control to group '53360de9-e8c7-4cf5-a864-389971142c12' in page 'd0171d51-ff84-4038-afc1-8800ab613160.System.WorkItemType.Details' in 'Agile_SS365_3.Requirement'. Error: Failed request: (503)

2.Second time I deleted the Process template half imported in Target site and retrigged export and i got the below error:
[VERBOSE] [2019-11-05T23:14:20.985Z] Begin step 'Add field 'System.State' to work item type 'Agile_SS365_3.ConfigurationDeliverable''.
[VERBOSE] [2019-11-05T23:14:21.799Z] Exception message:Failed request: (503)
Call stack:Error: Failed request: (503)
    at RestClient.<anonymous> (C:\Users\T970651\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\T970651\AppData\Roaming\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] [2019-11-05T23:14:21.808Z] Import failed, see log file for details. Failed to add field 'System.State' to work item type 'Agile_SS365_3.ConfigurationDeliverable', see logs for details.

1.I am not sure why it is failing for the first attempt with error related to control.
2.I assume during the second attempt it is failing because the field already exists(not deleted on deleting the process template) in the target Organization. Can you please advice me the best way to handle this. I don't find a was to customize the field names before migration in Process Migrator. Can you please help

Thanks and Regard,
Sakthi

**Comment by suchir001** [comment]
We also ended up with several problems like this. Probably ran it like a total of 20 times. We solved each of those problems one by one

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
