### ISSUE TITLE
Custom Completed State Category - now supported in inherited process templates, but fails during migration

### ISSUE THREAD

**Issue by monteholyfield** [microsoft/process-migrator#42]
We are now able to create a custom value for the 'Completed' State Category.  However, this fails with the following error when running the process-migrator.  In this case, I created a Completed State named 'Approved' in the source work item template.

```
[VERBOSE] [2020-01-11T00:43:41.088Z] Exception message:VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
Call stack:Error: VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
    at RestClient.<anonymous> ([...]\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled ([...]\npm\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] [2020-01-11T00:43:41.106Z] Import failed, see log file for details. Unable to create/hide/update state 'Approved' in 'HWDev.HWECRApproval' work item type, see logs for details
```

**Comment by liang2zhu1** [comment]
@monteholyfield  hey sorry can't commit when I can look deep into this but can you attach exported xml?  My best guess at this point stays the code shall not try to update the value on server but it's likely marked as 'non default' during export because of the new feature you mentioned on completed category customization.

**Comment by monteholyfield** [comment]
Hi Liang,

Thank you for response.

Is there a way to export XML from an inherited process template?  I see this section in the exported JSON from the process-migrator.  The yellow ‘Approved’/’Completed’ value is the one causing trouble.  Let me know if you need to see the entire exported JSON file.

    {
      "workItemTypeRefName": "HWValidation.HWECR",
      "states": [
        {
          "id": "195e4dbf-a0ff-4dcb-ae07-ca4a504fc7b7",
          "name": "Pending Review",
          "color": "D5D5D5",
          "stateCategory": "Proposed",
          "order": 1,
          "url": "https://dev.azure.com/MR-HW/_apis/work/processDefinitions/a820e108-d03d-4ccc-ac38-6798f2fa6670/workItemTypes/HWValidation.HWECR/states/195e4dbf-a0ff-4dcb-ae07-ca4a504fc7b7"
        },
        {
          "id": "ca79fffe-339c-4448-88a4-c9aa8206f6fe",
          "name": "Rejected",
          "color": "e60017",
          "stateCategory": "InProgress",
          "order": 2,
          "url": "https://dev.azure.com/MR-HW/_apis/work/processDefinitions/a820e108-d03d-4ccc-ac38-6798f2fa6670/workItemTypes/HWValidation.HWECR/states/ca79fffe-339c-4448-88a4-c9aa8206f6fe"
        },
        {
          "id": "ccce3681-df84-4dc6-9289-3219cabe03dc",
          "name": "Approved",
          "color": "4E9D5D",
          "stateCategory": "Completed",
          "order": 3,
          "url": "https://dev.azure.com/MR-HW/_apis/work/processDefinitions/a820e108-d03d-4ccc-ac38-6798f2fa6670/workItemTypes/HWValidation.HWECR/states/ccce3681-df84-4dc6-9289-3219cabe03dc"
        }
      ]
    }

Thanks,
Monte


--
[cid:image001.png@01D5DA84.66A5FC70]<https://www.microsoft.com/microsoft-hololens/en-us>
Monte Holyfield
Senior Hardware Engineering Program Mgr
Microsoft HoloLens

Office: +1 (425) 421-1355
Mobile: +1 (425) 505-1433
monte.holyfield@microsoft.com<mailto:monte.holyfield@microsoft.com>

[Linkedin]<https://www.linkedin.com/in/monteholyfield>

**Comment by ross-bohr** [comment]
We're hitting the exact same problem with process-migrator - for a custom state in "Completed" category on a custom work item type, even though this works beautifully in the web UI of AzDO:

[VERBOSE] [2020-04-07T12:40:36.712Z] Exception message:**VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.**
Call stack:Error: VS403093: Team Services currently does not support changes to 'Completed' category. Choose a different category.
    at RestClient.<anonymous> (C:\npm\prefix\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:173:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\npm\prefix\node_modules\process-migrator\node_modules\typed-rest-client\RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by AjKundnani** [comment]
Below is the API call made when modifying through browser:
**Request URL**: https://dev.azure.com/{OrgName}/_apis/work/processes/{processid}/workItemTypes/{processname}.Feature/states
**Request Method**: POST
**Status Code**: 201 
**Payload**
{name: "Complete", stateCategory: "Completed", color: "4E9D5D", order: null}
color: "4E9D5D"
name: "Complete"
order: null
stateCategory: "Completed"

**Comment by tasb** [comment]
Hi,
Any update on this issue?
I'm getting the same error even changing for a already definined Completed state
Thanks

**Comment by chrisreddington** [comment]
+1 - Also just encountered this

**Comment by Damandan** [comment]
+1, This issue is still present.

**Comment by Damandan** [comment]
@liang2zhu1 Any word on when you might have a look at this?

**Comment by dwjobling** [comment]
@liang2zhu1 Can you let us know if someone is working on this particular issue?  If not the community may be able to assist but we'd like to know we're not duplicating effort.  We're encountering this issue now more often and its a spanner in the works of our automation.

**Comment by christian-skj** [comment]
#83
