### ISSUE TITLE
Failed to connect to account using personal access token '<omitted>' provided, check url and token.

### ISSUE THREAD

**Issue by Prateek1584990** [microsoft/process-migrator#46]
Hi Team,

When we are trying to import the process .json into Azure Devops Server 2019 , we are getting below error from the process migrator tool.

Failed to connect to account https://FQDN/tfs/Collection Name using personal access token '<omitted>' provided, check url and token.

Request your help in fixing this issue.

**Comment by jkocsis3** [comment]
Seeing the same issue as well with Azure Devops Sever 2019. 
Token is less than a day old, has full access to all collections.
Using SSL and hitting https://<Azure url>/<colectionName> as the sourceAccountUrl.

**Comment by eduardobbs** [comment]
I am getting this error when trying to export from a local TFS instance (Version Dev17.M153.3).

**Comment by xg578962913** [comment]
I also encountered such a problem. Is there any way to solve it

**Comment by liang2zhu1** [comment]
Happened to look at a different issue and noticed node.js ADO client appears not working for collection-scoped token, try with a token with access to 'all organizations'

**Comment by Roberto8004** [comment]
Tuve el mismo problema. El mismo se me dio por tener Azure Devops 2019 on premise con certificado autofirmado.
Para que el script node funcione hay que agregar la variable de entorno 
NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by AminTi** [comment]
HI guys if you still have the same issue let me know, We just merged an update.
