### ISSUE TITLE
398441

### ISSUE THREAD

**Issue by fwilkinson** [microsoft/process-migrator#50]
Good morning.  I'm sure it is something simple but I'm getting an error when I try to run the process-migrator -- mode=export --config=./configuration.json command.  For my sourceURL I have tried both https://XXXXXX.visualstudio.com and https://dev.azure.com/XXXXXX and every time I run the command, I get [Configuration validation] Missing or invalid source account url: 'undefined'

It looks like I ran the installation in the C:\Windows\System32 so that is where I am running the command.  
Any help?
Thank you,
Ford

**Comment by fwilkinson** [comment]
I was putting the URL in the wrong place.  It should be "sourceAccountUrl":"https://XXXX.visualstudio.com"

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you .
