### ISSUE TITLE
Error with special characters.  

### ISSUE THREAD

**Issue by swalczewski** [microsoft/process-migrator#53]
We are getting the following error due to special characters in the field name.  We are unable to modify the field name to make the script happy.  Are there any workarounds that someone can suggest? 

"
Exception message:VS402800: The name 'CustomerName(IDN)' is invalid. Names cannot be empty, exceed 128 characters, be a number, or contain the following characters: '.,;~:/\*|?"&%$!+=()[]{}<>-์.
"

Thanks in advance,

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
