### ISSUE TITLE
"Current user is not member of group" Condition in Rule is ignored

### ISSUE THREAD

**Issue by CaRniFeXeR** [microsoft/process-migrator#54]
When using a "Current user is (not) member of group"-Rule no condition is saved in export JSON.
Rule in DevOps:
![image](https://user-images.githubusercontent.com/39064983/102088090-b748b780-3e1a-11eb-9b0e-b90e8230d630.png)

Rule in exported JSON-File:
```
    {
          "id": "2e9c6ee1-9e10-46d2-8e49-49132d8e5c41",
          "friendlyName": "\"Manuell Config Steps\" Read Only For Ext-Users",
          "conditions": [],
          "actions": [
            {
              "actionType": "$makeReadOnly",
              "targetField": "Custom.ManualConfigsteps",
              "value": null
            }
          ],
          "isDisabled": false,
          "isSystem": false
        },

```

**Comment by AminTi** [comment]
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for you.
