### ISSUE TITLE
Config File Example

### ISSUE THREAD

**Issue by TSPFounder** [microsoft/process-migrator#58]
Would you please provide an example of the configuration.jsonc file

**Comment by mauricionit** [comment]
{
    "sourceAccountUrl": "https://dev.azure.com/org-name1",
    "sourceAccountToken": "your-personal-access-token",
    "targetAccountUrl": "https://dev.azure.com/org-name2",
    "targetAccountToken": "your-personal-access-token",
    "sourceProcessName": "the-name-of-your-process",
    "targetProcessName": "you-can-let-it-in-blank",
    "options": { (YOU CAN LET IT AS IT IS IN THE "DOCS")
        "processFilename": "Set to override default export file name, remove from param name", 
        "logLevel":"Set to override default log level (Information), remove from param name",
        "logFilename":"Set to override default log file name, remove from param name",
        "overwritePicklist": false
    }
}

@TSPFounder

**Comment by MOlausson** [comment]
Cleaning up old issues, this is documented in the project readme so closing for now.

**Comment by TSPFounder** [comment]
Thank you very much!
