### ISSUE TITLE
Keyboard listener added ??

### ISSUE THREAD

**Issue by czechdude** [microsoft/process-migrator#72]
Hello, why there is a line in log:
[VERBOSE] [2019-11-27T09:49:36.184Z] Keyboard listener added
???
It seems VERY suspicious..
Thanks for clearing this up.

**Comment by MOlausson** [comment]
Hi @czechdude , I'm cleaning up old issues. In case you didn't figure this out - the logging comes from https://github.com/microsoft/process-migrator/blob/a9ff7f0abebb55ab41e88d5ba41e84e96d879964/src/nodejs/NodeJsUtilities.ts#L32 where a listener for keyboard input is registered. In short, it listens for if the user press "q" to stop the migration.
