### ISSUE TITLE
Import failed, see log file for details. Process payload file 'C:empevOpsrocess.json' does not exist.

### ISSUE THREAD

**Issue by yyl15** [microsoft/process-migrator#76]
I was able to import a few months back but I am hitting this error message today, it is just a simple import with parameters:
targetAccountUrl, targetAccountToken, targetProcessName and processFilename.

**Comment by yyl15** [comment]
Content of error log

[INFORMATION] [2023-01-31T18:18:17.649Z] Full log is sent to 'C:\Users\123456\output\processMigrator.log' 
[VERBOSE] [2023-01-31T18:18:17.659Z] Keyboard listener added
[ERROR] [2023-01-31T18:18:17.661Z] Import failed, see log file for details. Process payload file 'C:empevOpsrocess.json' does not exist.

**Comment by yyl15** [comment]
FYI, the migrate and export works well, only import has issue.

**Comment by MOlausson** [comment]
@yyl15, sorry for the lack of response, we're a new team taking over maintaining the tool so catching up on the backlog. Did you get this figured out? It looks like an honest mistake where the string literal in json needs to use double backslashes.

```json
"processFilename": "c:\\process-migrator\\output\\process.json"
```
