### ISSUE TITLE
command not found , when try to run in azure pipeline

### ISSUE THREAD

**Issue by ADITYA986178** [microsoft/process-migrator#77]
I was trying to run process migrator in Azure Pipeline by directly running in Console as well as through Nodejs child process in both the case it is giving error as process-migrator command not found . Though npm install was successful and process-migrator is there under node_modules .

**Comment by ADITYA986178** [comment]
sh: 1: process-migrator: not found
##[error]Bash exited with code '127'.

**Comment by AminTi** [comment]
process-migrator --mode=migrate --config= ./configuration.json run this command 
We will release an update addressing previous problems. For new issues, create a ticket, and we'll resolve it promptly. Thank you for your support and understanding.
