### ISSUE TITLE
Passing the PAT

### ISSUE THREAD

**Issue by MrHinsh** [Microsoft/process-migrator#8]
I need to run this as part of a VSTS CD process. How do I pass the configuration options without using the Config file?

It is not going to be feasible or posible to write the PAT token into a file!

**Comment by liang2zhu1** [comment]
@MrHinsh  I hear you , a few our other tool (Like https://github.com/Microsoft/vsts-work-item-migrator) also does same. Would it work for you say we support PAT direclty on command line?

**Comment by MrHinsh** [comment]
It will, but..

You need to wrap this in a Build Task. The only way this is ever going to be run is part of automation, and we have that nice CD pipeline sitting right there. 😁

**Comment by liang2zhu1** [comment]
Sure - so what's your favorable way to pass PAT then? environment variable or something else? I'm just not sure what works for your need here.

**Comment by MrHinsh** [comment]
If you support PAT directly on the command line then that will mitigate the immediate problem.

But I think if you took the time to build a VSTS Build task for this you would figure it out. My favourite way to pass tokens is using a shared service in VSTS or worst case as a build task variable. I don't care how the insides work...
