### ISSUE TITLE
TFS 2017 based process template migration to AzureDevOps Services

### ISSUE THREAD

**Issue by ktdixit** [microsoft/process-migrator#82]

**Comment by ktdixit** [comment]
Does the migration utility supports migrating process template customised in TFS 2017 environment to AzureDevOps Services? Please confirm

**Comment by MOlausson** [comment]
Hi @ktdixit, did you figure this out? The process migrator only supports migration of inherited processes, which was introduced with TFS 2019. For xml based collections you can use the [download/upload process template](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/guidance/manage-process-templates) features on the server.

**Comment by ktdixit** [comment]
@MOlausson Thanks. So, I have to download the process template from TFS 2017 and upload in TFS 2019... Then use the process migrator from TFS 2019 to AzureDevOps Services.. Correct?

**Comment by MOlausson** [comment]
@ktdixit ah, thanks for the additional context, now I understand your scenario. In this case you don't need to use the process migrator at all, instead check out https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/import-process?view=azure-devops#import-a-process-from-an-on-premises-azure-devops.

**Comment by ktdixit** [comment]
@MOlausson unfortunately our AzureDevOps Services organisation doesn’t support “Hosted XML process model”. So, we don’t have an option to “Import Process”. 

Any other recommendations?
