### ISSUE TITLE
unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by matchstickhero** [microsoft/process-migrator#88]
Receiving this error. URL and PAT are valid.

[INFORMATION] [2023-08-24T17:45:50.810Z] Export process started.
[VERBOSE] [2023-08-24T17:45:50.811Z] Begin step 'Get source process Id from name'.
[VERBOSE] [2023-08-24T17:45:50.953Z] Exception message:write EPROTO 2C1A0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

Call stack:Error: write EPROTO 2C1A0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[ERROR] [2023-08-24T17:45:50.955Z] Export failed, see log file for details. Error getting processes on source account 'https://[redacted].com, check account url, token and token permissions.

**Comment by AminTi** [comment]
Hello! It seems there might be an issue related to either the authentication token or the source URL. Can you let me know when you're free for an online session? That way, we can work together to figure out what's going wrong. Thank you!
