### ISSUE TITLE
Why put Target for Export?

### ISSUE THREAD

**Issue by MrHinsh** [Microsoft/process-migrator#9]
The documentation implies that entering the target information is required for Export, but it should not be.

**Comment by liang2zhu1** [comment]
Do you refer to the line below? Thanks for the feedback I can be explicit about this to say it's not used on 'export' mode but would love to know which part caused you think it's implied this is required for export? Or is it something else causing confusion? 

    "targetAccountUrl": "Required in 'import'/'migrate' mode, target account url.",

**Comment by liang2zhu1** [comment]
I made some improvements to the document, please let me know if you have further feedback.
