### ISSUE TITLE
TFS- ADO process migration

### ISSUE THREAD

**Issue by radhiam** [microsoft/process-migrator#91]
Hi Team, 

is it possible to migrate the process from TFS to Azure Devops Services?
I have to migrate the Project by Project from TFS to ADO. I don't see any tools which helps to migrate the Process template from TFS to ADO.
 If yes. Please guide me how to use it ?

**Comment by MOlausson** [comment]
@radhiam the process migrator supports Azure DevOps Server (2019 and later) to Azure DevOps Services for inherited processes, not for the old xml process templates unfortunately.
