### ISSUE TITLE
Migration completes but some backlog items are blank with no data

### ISSUE THREAD

**Issue by wickens** [microsoft/process-migrator#92]
Version: `devopsmigration 14.2.2+Branch.master.Sha.e09eca9a6911ac77ecd0e162a29cd4aa632c3ad4`

Many of the backlog items in the destination are blank:
<img width="422" alt="image" src="https://github.com/microsoft/process-migrator/assets/72025547/f09c5209-96af-46fd-b047-352233ee0778">
<img width="1725" alt="image" src="https://github.com/microsoft/process-migrator/assets/72025547/427acac8-0212-412b-b5b1-18c4fbcfcb96">

- I am migrating a project from one org to another, with the same process, both on Azure DevOps. I  have no field maps (as I want a like for like migration). 
- In the logs, that are 3 types of error I can see (repeated many times)
- The issue seemingly occurs for all backlog item types, though not for every item.

Errors in the log file:

- (258) System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Page not found.
- Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Azure DevOps Server administrator. ---> System.Web.Services.Protocols.SoapException: VS403417: ChangedBy value cannot be empty when BypassRules is specified
-  ArgumentException System.ArgumentException: An item with the same key has already been added.

Any suggestions on what might be the root cause?

**Comment by aldurbey85** [comment]
I'm working with Marc on this independently and have the same issue

**Comment by MOlausson** [comment]
@wickens @aldurbey85 I assume you've run the process migrator as a first step. What tool are you using for the work item migration? The source ref looks like a reference to https://github.com/nkdAgility/azure-devops-migration-tools/ and unless you suspect this is related to migrating the processes I suggest raising a ticket there.

**Comment by MrHinsh** [comment]
This is a configuration issue. Change `SkipToFinalRevisedWorkItemType` to `false`.
