### ISSUE TITLE
process-migrator not migrating Team Project

### ISSUE THREAD

**Issue by JAlexander22** [microsoft/process-migrator#96]
Hi, 
I'm new to this but am currently trying to use process-migrator to migrate the process. However, I'm unable to migrate Team Projects. Is this a limitation of process-migrator? or am I utilizing or missing configuration? 

I haven't changed anything apart from the configuration information that was required on the tutorial guide but apart from that not sure what I'm doing wrong. 

Could someone assist? 
Thank you

**Comment by MOlausson** [comment]
Hi @JAlexander22, which tutorial are you following? This tools specifically helps migrating custom work item processes, not work items. Are you also looking at migrating the work items or what do you mean with migrating Team Project?

**Comment by JAlexander22** [comment]
Hi MOlausson.  on ADO in All Processes. There is a tab next to the Description called "Team Project" I was wondering if we could use Process-migrator to move over Team Projects as well. But as your reply states only work items which isn't a problem.

Thanks for your response
