### ISSUE TITLE
"Encountered unkonwn error" on step 'Get artifacts from source process'

### ISSUE THREAD

**Issue by marnheus** [microsoft/process-migrator#97]
I get what looks like a timeout on pretty much the first step of the migration project
<img width="871" alt="image" src="https://github.com/microsoft/process-migrator/assets/7369341/0ef83ac2-0fa6-4e3e-a43d-d7f3910ae60b">

What's even stranger is that when I look at the usage on my source ADO org, I see the API calls and they are not in error

Is there someone who has an idea on what could go wrong here?

**Comment by marnheus** [comment]
Btw, the log file doesn't contain anything more than the console output

**Comment by vikas1189** [comment]
I also faced the exact similar issue. It looks the issue replicates when there is a hyphen '-' in the AZD organization name. Didn't found a solution for this.

**Comment by MOlausson** [comment]
@marnheus @vikas1189 thanks for reporting this. I did a quick test and got the same problem intermittently on Windows. Which platform are you on?

**Comment by marnheus** [comment]
Windows 11

**Comment by vikas1189** [comment]
> @marnheus @vikas1189 thanks for reporting this. I did a quick test and got the same problem intermittently on Windows. Which platform are you on?

I am Windows 10.

**Comment by MOlausson** [comment]
Ok. Interestingly it works 100% on Linux when I run it for instance in a GitHub codespace. But I get the same problem on Windows so will continue to investigate. Best guess at the moment is that it's network related but can be completely wrong here.

**Comment by marnheus** [comment]
I tried to run the tool in a github codespace and it did work. It looks there is an issue with the windows implementation of the package.

**Comment by MOlausson** [comment]
Today it works consistently on Windows as well, feel network related so we'll see if we can implement retries to mitigate for latency/throttling etc.

**Comment by marnheus** [comment]
Seems to be working for me too now. Guess it was a transient (but long ;)) network issue
