### ISSUE TITLE
Access requirements

### ISSUE THREAD

**Issue by code-on-git** [microsoft/process-migrator#98]
When I read the documentation I got the impression that the PAT's in the config file are all you need to migrate a process.
But it turns out that I had to be logged in with my own Azure Devops admin account as well. Otherwise I get this error message:
```VS402356: You do not have the permissions required to perform the attempted operation on this process.```

Is this written somewhere in the documentation or is it a bug?

**Comment by MOlausson** [comment]
@code-on-git was this in the export or import phase?

**Comment by code-on-git** [comment]
It was in the import phase.

**Comment by MOlausson** [comment]
Thanks. Which Azure DevOps versions are you migrating from and to? The PAT should only need the "Work Items 'Read, Write, & Manage" permission scope.

**Comment by code-on-git** [comment]
From: Version Dev19.M235.1 (AzureDevOps_M235_20240304.10)
To: Version Dev19.M235.1 (AzureDevOps_M235_20240311.1)

**Comment by AminTi** [comment]
Hi, I just tested it, and you don't need to be logged in
<img width="689" alt="Screenshot 2024-05-08 at 16 15 24" src="https://github.com/microsoft/process-migrator/assets/54841342/e7d7b7cd-3b3c-4655-a9b2-ebe701af327f">

**Comment by Bifeater** [comment]
@code-on-git Had the same issue.
Problem was that i set the rights in the token, but my user itself did not have permissions to create a process on organisation level.
I did not find that requirement explicitely mentioned in the docu.
