### ISSUE TITLE
 Process import validation failed. Field in target Collection conflicts with 'field-name' field with a different reference name or type.

### ISSUE THREAD

**Issue by code-on-git** [microsoft/process-migrator#99]
What does this message mean?
I have no idea of where to start looking for something to fix.

**Comment by devIramos** [comment]
Hi!

Let me explain what's happening and the solutions I found:

The fields are shared across all processes. This means if you create a field called "Due Date" in process A, and later create process B, the "Due Date" field will be accessible and usable in the new process.

Therefore, the error is essentially that the field exists in both the source and destination processes, but with different data types. However, the error can also occur even if the data types are exactly the same.

Option 1:
Look for the field in the Fields tab at the level of all Processes, both in the source and destination. Delete the field in the destination process, as it will be generated again anyway.

Option 2:
Completely delete the destination process (be careful not to have any projects already assigned). This will also delete its fields, so the new process will regenerate everything from scratch.

Option 3:
The code needs a change to identify when a field in the source exists in the destination with exactly the same characteristics. The field should be ignored as it does not need to be created again, but the ID must be identified to be used later in the different work items.

In my case, I used option 1.

I hope this helps! Regards!
